# Generated by Django 3.2 on 2021-04-28 14:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('13721d30-f5ad-48c9-ab4b-aa05a96bd0bb'), primary_key=True, serialize=False, verbose_name='Address id')),
                ('line', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e169e509-246c-4249-96d4-f8af3070f93e'), primary_key=True, serialize=False, verbose_name='Booking id')),
                ('reference', models.CharField(max_length=20)),
                ('status', models.CharField(default='inactive', max_length=20)),
                ('pay', models.CharField(default='unpaid', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5fab0c7e-51bd-4161-b4c5-47ee47866150'), primary_key=True, serialize=False, verbose_name='Permission id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Permission name')),
                ('description', models.CharField(max_length=500, verbose_name='Permission description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('55b10aa0-03da-41aa-827c-1f8e0d0ccfd3'), primary_key=True, serialize=False, verbose_name='Role id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Role name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Role description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b821f25f-d553-42e5-bd63-e7a9aa8c3e4a'), primary_key=True, serialize=False, verbose_name='Bus id')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Bus name')),
                ('registration_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('9bb2cd90-69fe-4644-8bbf-8d676e89a877'), primary_key=True, serialize=False, verbose_name='Person unique id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Person email')),
                ('last_name', models.CharField(max_length=50, verbose_name='Person last name')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Person first name')),
                ('password', models.CharField(max_length=150, verbose_name='Person password')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Person phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.address')),
                ('permission', models.ManyToManyField(to='api.Permission')),
                ('role', models.ManyToManyField(to='api.Role')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6cb58116-67dc-4512-a466-a77207b4402f'), primary_key=True, serialize=False, verbose_name='Payment id')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=6)),
                ('status', models.CharField(default='unpaid', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4f7f5993-1ebd-4b8d-9813-91e2f357e5af'), primary_key=True, serialize=False, verbose_name='Journey id')),
                ('name', models.CharField(max_length=20, verbose_name='Journey name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Journey information')),
                ('price', models.DecimalField(decimal_places=6, max_digits=6, max_length=10000000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('608141ca-0546-41e3-a523-2e151d96802c'), primary_key=True, serialize=False, verbose_name='Destination Id')),
                ('location', models.CharField(max_length=50, verbose_name='Destination location or area')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Destination information')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('journey', models.ManyToManyField(to='api.Journey')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person'),
        ),
    ]
