# Generated by Django 3.2 on 2021-04-28 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='api.Permission'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('889b323c-72d8-41eb-8b0b-4f3cb59efc19'), primary_key=True, serialize=False, verbose_name='Address id'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.UUID('018b92d4-615c-474d-baf6-6daa238765fa'), primary_key=True, serialize=False, verbose_name='Booking id'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af96f630-4391-49a6-adab-8d4483bd99ab'), primary_key=True, serialize=False, verbose_name='Destination Id'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b6bf4b1-ec8d-4753-bc1a-abde01262a26'), primary_key=True, serialize=False, verbose_name='Journey id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59d88752-0cc4-49aa-aee1-3038679a8427'), primary_key=True, serialize=False, verbose_name='Payment id'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5b44e69-2757-4c32-89ba-d8abf0d4d330'), primary_key=True, serialize=False, verbose_name='Permission id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b8978ef-4dbe-4552-bcc2-353c5df2761d'), primary_key=True, serialize=False, verbose_name='Person unique id'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f74d0c68-1bc3-4c42-be26-b0d26ddd5ef3'), primary_key=True, serialize=False, verbose_name='Role id'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ae3bc64-ffb6-4028-9598-2e8b4868833f'), primary_key=True, serialize=False, verbose_name='Bus id'),
        ),
    ]
